routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/* the route will get the 'blog from url, then add n array "[]" for all the peramiters', where it 'uses' the blog controller index action and it is determaied 'as' blog.index */
//Route::get('blog', ['uses' => 'BlogController@getIndex', 'as' => 'blog.index'])

Route::group(['middleware' => ['web']], function () {
	// Authentication routes
	Route::get('login', 'Auth\AuthController@getLogin');
	Route::post('login', 'Auth\AuthController@postLogin');
	Route::get('logout', 'Auth\LoginController@logout')->name('logout');


	// Registration Routes
	Route::get('register', 'Auth\AuthController@getRegister');
	Route::post('register', 'Auth\AuthController@postRegister');

	// Password Reset Routes
	Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
	Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
	Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
	Route::post('password/reset', 'Auth\ResetPasswordController@reset');

	Route::get('blog/{slug}', ['as' => 'blog.single', 'uses' => 'BlogController@getSingle'])->where('slug', '[\w\d\-\_]+');
	Route::get('blog', ['uses' => 'BlogController@getIndex', 'as' => 'blog.index']);
	Route::get('contact', 'PagesController@getContact');
	Route::get('about', 'PagesController@getAbout');
	Route::get('/', 'PagesController@getIndex');
	Route::resource('posts', 'PostController');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    //
}

// this pulls every post in DB
//Post::all()

// this would pull that specific post from the DB
//Post::where('title' => 'My First Title')->get()

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Post;
use Session;

/*anything in blue you want to add it to the list above */

class PostController extends Controller
{

    public function __construct() {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // create a variable and store all the blog posts in it from the database
        // post all will take all the blog posts from the database and paginate them
        $posts = Post::orderBy('id', 'desc')->paginate(10);

        // return a view and pass it in the above variable 
        return view('posts.index')->withPosts($posts);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // validate the data
        // validation rules are what you want it to do
        // adding to rules together you use |
        $this->validate($request, array(
                'title' => 'required|max:255', 
                'slug' => 'required|alpha_dash|min:5|max:255|unique:posts,slug',
                'body' => 'required'
            ));

        // store in database
        $post = new Post;

        $post->title = $request->title;
        $post->slug = $request->slug;
        $post->body = $request->body;

        $post->save();

        Session::flash('success', 'The blog post was successfully saved');

        // redirect to another page
        // after redirected the route is posts show page
        // brings you to the dynamic post that has just been made
        return redirect()->route('posts.show', $post->id);
    }

    /**
     * Display the specified resource.
     * render the view pass the viriable called post and set the virable and the view equal to our posts which should be matching the database
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::find($id);
        return view('posts.show')->withPost($post);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // find the post in the database and save as a variable
        $post = Post::find($id);
        // return the view and pass in the variable we previouly created
        return view('posts.edit')->withPost($post);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // it will accept information from the request from the form field data it will accept all of that take it validate it and store it in the database !-->
        $post = Post::find($id);
        if ($request->input('slug') == $post->slug) {
        $this->validate($request, array(
                'title' => 'required|max:255',
                'body' => 'required'
            ));
        } else {
        // Validate the date       
        $this->validate($request, array(
                'title' => 'required|max:255',
                'slug' => 'required|alpha_dash|min:5|max:255|unique:posts,slug',
                'body' => 'required'
            ));
    }

        // save the data to the database
        $post = Post::find($id);

        // input identify something from the post input that was passed in !-->
        $post->title = $request->input('title');
        $post->slug = $request->input('slug');
        $post->body = $request->input('body');
        // this will now save and change the updated timestamp 
        $post->save();
        // set flash data with success message 
        Session::flash('success', 'This post was successfully saved.');
        // redirect with the flash data to posts.show 
        return redirect()->route('posts.show', $post->id);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::find($id);

        $post->delete();

        Session::flash('success', 'The post was successfully deleted');
        return redirect()->route('posts.index');
    }
}

resources/views/posts/create.blade.php
@extends('main')

@section('title', '| Create new post')

@section('stylesheets')

	{!! Html::style('css/parsley.css') !!}

@endsection

@section('content')

	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<h1>Create New Post</h1>
			<hr>
			<!-- this form is the same as a form tag but offers more Csrf protection secutrity feature !-->
			<!-- see php artisan route:list for detials !-->
			<!-- passing route parimiter going to post store in db, passing id the label always matching the column name of the db, the Title: is the title that will be above the form name on the browser, then create the form field create text and should submit it under the title field and that theyre linked, default value is null, second paramitor create array pass class to know what classes to give this, form control basicallt is the style !-->
			{!! Form::open(['route' => 'posts.store', 'data-parsley-validate' =>'']) !!}
  				{{ Form::label('title', 'Title:') }}
  				{{ Form::text('title', null, array('class' => 'form-control', 'required' => '', 'maxlength' =>'255')) }}

  				{{ Form::label('slug', 'Slug:') }}
  				{{ Form::text('slug', null, array('class' => 'form-control', 'required' => '', 'minlength' => '5', 'maxlength' => '255') ) }}

  				<!-- matching the column and the label for the db !-->

  				{{ Form::label('body', 'Post Body:') }}
  				{{ Form::textarea('body', null, array('class' => 'form-control', 'required' => '')) }}

  				<!-- submit is button then text the user sees, array give class btn is button, btn success is green, btn-lg is button large, btn-block is making it full width !--> 

  				{{ Form::submit('Create Post', array('class' => 'btn btn-success btn-lg btn-block', 'style' => 'margin-top: 20px;')) }}
			{!! Form::close() !!}
		</div>
	</div>

@endsection

@section('scripts')

	{!! Html::script('js/parsley.min.js') !!}

@endsection

resources/views/posts/edit.blade.php
@extends('main')

@section('title', '| Edit Blog Post')

@section('content')
    <div class="row">
        <div class="col-md-8">
            <form method="POST" action="{{ route('posts.update', $post->id) }}">
                {{ csrf_field() }}
                {{ method_field('PUT') }}
                <div class="form-group">
                    <label for="title">Title:</label>
                    <textarea type="text" class="form-control input-lg" id="title" name="title" rows="1" style="resize:none;">{{ $post->title }}</textarea>

            <div class="form-group">
                <label for="body">Slug:</label>
                    <textarea type="text" class="form-control input-lg" id="slug" name="slug" rows="1" style="resize:none;">{{ $post->slug }}</textarea>
                </div>
            </div>
                <div class="form-group">
                    <label for="body">Body:</label>
                    <textarea type="text" class="form-control input-lg" id="body" name="body" rows="10" style="resize:none;">{{ $post->body }}</textarea>
                </div>
            
        </div>
        <div class="col-md-4">
            <div class="well">
                <dl class="dl-horizontal">
                    <dt>Created At:</dt>
                    <dd class="text-muted">{{ date('M j, Y H:ia ', strtotime($post->created_at)) }}</dd>
                </dl>

                <dl class="dl-horizontal">
                    <dt>Last Updated:</dt>
                    <dd class="text-muted">{{ date('M j, Y h:ia ', strtotime($post->updated_at)) }}</dd>
                </dl>
                <hr>
                <div class="row">
                    <div class="col-sm-6">
                        <a href="{{ route('posts.show', $post->id) }}" class="btn btn-danger btn-block">Cancel</a>
                    </div>
                    <div class="col-sm-6">
                        <button type="submit" class="btn btn-success btn-block">Save Changes</button>
                    </div>
    </form>
                </div> <!-- /row -->
            </div> <!-- /well -->
        </div> <!-- /col-md-4 -->
    </div> <!-- /row -->
@endsection﻿

resources/views/posts/index.blade.php
@extends('main')

@section('title', '| All Posts')

@section('content')

	<div class="row">
		<div class="col-md-10">
			<h1>All Posts</h1>
		</div>
<!-- route will link to create a new blog post !-->
		<div class="col-md-2">
			<a href="{{ route('posts.create') }}" class="btn btn-lg btn-block btn-primary btn-h1-spacing">Create new post</a>	
		</div>
		<div class="col-md-12">
			<hr>
		</div>
	</div> <!-- end of row !-->

	<div class="row">
		<div class="col-md-12">
			<table class="table table-striped">
				<thead>
					<th>#</th>
					<th>Title</th>
					<th>Body</th>
					<th>Created at</th>
					<th></th>
				</thead>

				<tbody>
					<!-- loop that will continue to pull as long as there is another post avalible to show !-->
					<!-- this is setting the echo to display the data from the db these will be shown in the titles above !-->

					<!-- the substring will take only the first 50 characters and display them on the page !-->

					<!-- the string lengh will check to see if the body text is greater than 50 if so thats what the ? is used for then ... then if it isnt greater used by the : then do nothing !--> 
					@foreach ($posts as $post)

						<tr>
							<th>{{ $post->id }}</th>
							<td>{{ $post->title }}</td>
							<td>{{ substr($post->body, 0,50) }}{{ strlen($post->body) > 50 ? "..." : "" }}</td>
							<td>{{ date('M j, Y', strtotime($post->created_at)) }}</td>
							<td><a href="{{ route('posts.show', $post->id) }}" class="btn btn-default btn-sm">View</a> <a href="{{ route('posts.edit', $post->id) }}" class="btn btn-default btn-sm">Edit</a></td>
						</tr>

					@endforeach

				</tbody>
			</table>
			<!-- this will add the pages buttons on the all posts page !-->
			<div class="text-center">
				{!! $posts->links(); !!}
			</div>
		</div>
	</div>

@endsection

resources/views/posts/show.blade.php
@extends('main')

@section('title', '| View Post')

@section('content')

<!-- set the h1 equal to the value of the title colomn in the db !-->
<!-- set the p equal to the value of the body colomn in the db !-->
  <div class="row">
  	<div class="col-md-8">
		<h1>{{ $post->title }}</h1>
	
		<p class="lead">{{ $post->body }}</p>
	</div>

	<div class="col-md-4">
		<div class="well">

			<dl class="dl-horizontal">
			<label>Url Slug:</label>
				<!-- this post slug is how to pull directly from the db column !-->
				<p><a href="{{ route('blog.single', $post->slug) }}">{{ route('blog.single', $post->slug) }}</a></p>
			</dl>

			<dl class="dl-horizontal">
			<label>Created at:</label>
				<!-- this post created_at is how to pull directly from the db column !-->
				<p>{{ date('M j, Y h:ia', strtotime($post->created_at)) }}</p>
			</dl>
				<dt>Created at:</dt>
				<!-- this post created_at is how to pull directly from the db column !-->
				<p>{{ date('M j, Y h:ia', strtotime($post->created_at)) }}</p>
			</dl>

			<dl class="dl-horizontal">
				<label>Last updated:</label>
				<p>{{ date('M j, Y h:ia', strtotime($post->updated_at)) }}</p>
			</dl>

			<hr>
			<!-- this will take the html link route to post edit page, then the button name with the passed array for the post id that is shown on this page !-->
			<div class="row">
				<div class="col-sm-6">
				{!! Html::linkRoute('posts.edit', 'Edit', array($post->id), array('class' => 'btn btn-primary btn-block')) !!}
				
				</div>
			<!-- this will take the submit to delete, then the button name with the passed array for the post id that is shown on this page !-->
				<div class="col-sm-6">
				{!! Form::open(['route' => ['posts.destroy', $post->id], 'method' => 'DELETE']) !!}

				{!! Form::submit('Delete', ['class' => 'btn btn-danger btn-block']) !!}

				{!! Form::close() !!}
				</div>
			</div>
	
			<div class="row">
				<div class="col-md-12">
					{{ Html::linkRoute('posts.index', '<< Back to all Posts', [], ['class' => 'btn btn-default btn-block btn-h1-spacing']) }}
				</div>
			</div>
		</div>
	</div>
</div>

@endsection

<!-- this will add a well that will contain the created at time and a last updated at and an edit blue button and a red delete button theyre inside of a small column 6  !--> 